source "https://rubygems.org"

group :jekyll_plugins do
   gem "jekyll"
   gem "jekyll-default-layout"
   gem "jekyll-optional-front-matter"
   gem "jekyll-readme-index" -> README-index, Bad statement
   gem "jekyll-theme-primer"
   gem "jekyll-titles-from-headings"
end
