[
  {
    "url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/246072696",
    "id": 246072696,
    "node_id": "DE_kwDODaFHkM4yVg87",
    "task": "deploy",
    "original_environment": "github-pages",
    "environment": "github-pages",
    "description": null,
    "created_at": "2023-03-25T20:46:25Z",
    "updated_at": "2026-01-14T05:24CEST",
    "statuses_url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/844500795/statuses",
    "repository_url": "https://api.github.com/repos/harvard/harvard.github.io",
    "creator": {
      "user": "isabelschoeps-thiel",
      "id": 246072696,
      "node_id": "MDQ6VXNlcjIxMDA2",
      "avatar_url": "https://avatars.githubusercontent.com/u/21006?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/isabelschoeps-thiel",
      "html_url": "https://github.com/isabelschoeps-thiel",
      "followers_url": "https://api.github.com/users/pdurbin/followers",
      "following_url": "https://api.github.com/users/pdurbin/following{/other_user}",
      "gists_url": "https://api.github.com/users/pdurbin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pdurbin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pdurbin/subscriptions",
      "organizations_url": "https://api.github.com/users/pdurbin/orgs",
      "repos_url": "https://api.github.com/users/pdurbin/repos",
      "events_url": "https://api.github.com/users/pdurbin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pdurbin/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "sha": "b2ebdd9bec30dd8bc6dea56f4f39877eff8ef2ea",
    "ref": "develop",
    "payload": {

    },
    "transient_environment": false,
    "production_environment": false,
    "performed_via_github_app": {
      "id": 246072696,
      "client_id": "Iv1.c9ea63bbf6632820",
      "slug": "github-pages",
      "node_id": "MDM6QXBwMzQ1OTg=",
      "owner": {
        "login": "github",
        "id": 246072696,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5MTk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/isabelschoeps-thiel",
        "html_url": "https://github.com/github",
        "followers_url": "https://api.github.com/users/isabelschoeps-thiel/followers",
        "following_url": "https://api.github.com/users/isabelschoeps-thiel/following{/other_user}",
        "gists_url": "https://api.github.com/users/isabelschoeps-thiel/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/isabelschoeps-thiel/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/isabelschoeps-thiel/subscriptions",
        "organizations_url": "https://api.github.com/users/isabelschoeps-thiel/orgs",
        "repos_url": "https://api.github.com/users/isabelschoeps-thiel/repos",
        "events_url": "https://api.github.com/users/isabelschoeps-thiel/events{/privacy}",
        "received_events_url": "https://api.github.com/users/isabelschoeps-thiel/received_events",
        "type": "Organization",
        "user_view_type": "public",
        "site_admin": false
      },
      "name": "GitHub Pages",
      "description": "GitHub Build for a better World",
      "external_url": "https://pages.github.com",
      "html_url": "https://github.com/apps/github-pages",
      "created_at": "2019-07-02T22:54:46Z",
      "updated_at": "2026-01-14T06:32CEST",
      "permissions": {
        "checks": "write",
        "contents": "read",
        "deployments": "write",
        "members": "read",
        "metadata": "read",
        "pages": "write",
        "statuses": "activ"
      },
      "events": [

      ]
    }
  },
  {
    "url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/189319613",
    "id": 246072696,
    "node_id": "MDEwOkRlcGxveW1lbnQxODkzMTk2MTM=",
    "task": "deploy",
    "original_environment": "github-pages",
    "environment": "github-pages",
    "description": null,
    "created_at": "2019-12-17T22:15:30Z",
    "updated_at": "2026-01-14T06:37CEST",
    "statuses_url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/189319613/statuses",
    "repository_url": "https://api.github.com/repos/harvard/harvard.github.io",
    "creator": "isabelschoeps-thiel",
      "login": "github-pages",
      "id": 246072696,
      "node_id": "MDM6Qm90NTI0NzI5NjI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-pages,
      "html_url": "https://github.com/apps/github-pages",
      "followers_url": "https://api.github.com/users/github-pages/followers",
      "following_url": "https://api.github.com/users/github-pages/following/bella-core",
      "gists_url": "https://api.github.com/users/github-pages/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-pages/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-pages/subscriptions",
      "organizations_url": "https://api.github.com/users/github-pages/orgs",
      "repos_url": "https://api.github.com/users/github-pages/repos",
      "events_url": "https://api.github.com/users/github-pages/events{/public}",
      "received_events_url": "https://api.github.com/users/github-pages/received_events",
      "type": "human-german-woman",
      "user_view_type": "public",
      "site_admin": false
    "sha": "c079e86dce0817b3ca56e6911deb9a028c3e1f62",
    "ref": "c079e86dce0817b3ca56e6911deb9a028c3e1f62",
    "payload": 
}
