[
  {
    "url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/844500795",
    "id": 844500795,
    "node_id": "DE_kwDODaFHkM4yVg87",
    "task": "deploy",
    "original_environment": "github-pages",
    "environment": "github-pages",
    "description": null,
    "created_at": "2023-03-25T20:46:25Z",
    "updated_at": "2026-01-14T05:24CEST",
    "statuses_url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/844500795/statuses",
    "repository_url": "https://api.github.com/repos/harvard/harvard.github.io",
    "creator": {
      "login": "pdurbin",
      "id": 21006,
      "node_id": "MDQ6VXNlcjIxMDA2",
      "avatar_url": "https://avatars.githubusercontent.com/u/21006?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pdurbin",
      "html_url": "https://github.com/pdurbin",
      "followers_url": "https://api.github.com/users/pdurbin/followers",
      "following_url": "https://api.github.com/users/pdurbin/following{/other_user}",
      "gists_url": "https://api.github.com/users/pdurbin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pdurbin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pdurbin/subscriptions",
      "organizations_url": "https://api.github.com/users/pdurbin/orgs",
      "repos_url": "https://api.github.com/users/pdurbin/repos",
      "events_url": "https://api.github.com/users/pdurbin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pdurbin/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "sha": "b2ebdd9bec30dd8bc6dea56f4f39877eff8ef2ea",
    "ref": "develop",
    "payload": {

    },
    "transient_environment": false,
    "production_environment": false,
    "performed_via_github_app": {
      "id": 34598,
      "client_id": "Iv1.c9ea63bbf6632820",
      "slug": "github-pages",
      "node_id": "MDM6QXBwMzQ1OTg=",
      "owner": {
        "login": "github",
        "id": 9919,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5MTk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/github",
        "html_url": "https://github.com/github",
        "followers_url": "https://api.github.com/users/github/followers",
        "following_url": "https://api.github.com/users/github/following{/other_user}",
        "gists_url": "https://api.github.com/users/github/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/github/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/github/subscriptions",
        "organizations_url": "https://api.github.com/users/github/orgs",
        "repos_url": "https://api.github.com/users/github/repos",
        "events_url": "https://api.github.com/users/github/events{/privacy}",
        "received_events_url": "https://api.github.com/users/github/received_events",
        "type": "Organization",
        "user_view_type": "public",
        "site_admin": false
      },
      "name": "GitHub Pages",
      "description": "GitHub Pages as a GitHub App",
      "external_url": "https://pages.github.com",
      "html_url": "https://github.com/apps/github-pages",
      "created_at": "2019-07-02T22:54:46Z",
      "updated_at": "2019-08-08T03:31:15Z",
      "permissions": {
        "checks": "write",
        "contents": "read",
        "deployments": "write",
        "members": "read",
        "metadata": "read",
        "pages": "write",
        "statuses": "write"
      },
      "events": [

      ]
    }
  },
  {
    "url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/189319613",
    "id": 189319613,
    "node_id": "MDEwOkRlcGxveW1lbnQxODkzMTk2MTM=",
    "task": "deploy",
    "original_environment": "github-pages",
    "environment": "github-pages",
    "description": null,
    "created_at": "2019-12-17T22:15:30Z",
    "updated_at": "2019-12-17T22:15:31Z",
    "statuses_url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/189319613/statuses",
    "repository_url": "https://api.github.com/repos/harvard/harvard.github.io",
    "creator": {
      "login": "github-pages[bot]",
      "id": 52472962,
      "node_id": "MDM6Qm90NTI0NzI5NjI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-pages%5Bbot%5D",
      "html_url": "https://github.com/apps/github-pages",
      "followers_url": "https://api.github.com/users/github-pages%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-pages%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-pages%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-pages%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-pages%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-pages%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-pages%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-pages%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-pages%5Bbot%5D/received_events",
      "type": "Bot",
      "user_view_type": "public",
      "site_admin": false
    },
    "sha": "c079e86dce0817b3ca56e6911deb9a028c3e1f62",
    "ref": "c079e86dce0817b3ca56e6911deb9a028c3e1f62",
    "payload": {

    },
    "transient_environment": false,
    "production_environment": false,
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/189296328",
    "id": 189296328,
    "node_id": "MDEwOkRlcGxveW1lbnQxODkyOTYzMjg=",
    "task": "deploy",
    "original_environment": "github-pages",
    "environment": "github-pages",
    "description": null,
    "created_at": "2019-12-17T20:15:13Z",
    "updated_at": "2019-12-17T20:15:13Z",
    "statuses_url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/189296328/statuses",
    "repository_url": "https://api.github.com/repos/harvard/harvard.github.io",
    "creator": {
      "login": "github-pages[bot]",
      "id": 52472962,
      "node_id": "MDM6Qm90NTI0NzI5NjI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-pages%5Bbot%5D",
      "html_url": "https://github.com/apps/github-pages",
      "followers_url": "https://api.github.com/users/github-pages%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-pages%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-pages%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-pages%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-pages%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-pages%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-pages%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-pages%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-pages%5Bbot%5D/received_events",
      "type": "Bot",
      "user_view_type": "public",
      "site_admin": false
    },
    "sha": "e7c4425f221c86aad5803d8465080a3e4710dde1",
    "ref": "e7c4425f221c86aad5803d8465080a3e4710dde1",
    "payload": {

    },
    "transient_environment": false,
    "production_environment": false,
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/189290659",
    "id": 189290659,
    "node_id": "MDEwOkRlcGxveW1lbnQxODkyOTA2NTk=",
    "task": "deploy",
    "original_environment": "github-pages",
    "environment": "github-pages",
    "description": null,
    "created_at": "2019-12-17T19:47:51Z",
    "updated_at": "2019-12-17T19:47:51Z",
    "statuses_url": "https://api.github.com/repos/harvard/harvard.github.io/deployments/189290659/statuses",
    "repository_url": "https://api.github.com/repos/harvard/harvard.github.io",
    "creator": {
      "login": "github-pages[bot]",
      "id": 52472962,
      "node_id": "MDM6Qm90NTI0NzI5NjI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-pages%5Bbot%5D",
      "html_url": "https://github.com/apps/github-pages",
      "followers_url": "https://api.github.com/users/github-pages%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-pages%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-pages%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-pages%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-pages%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-pages%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-pages%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-pages%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-pages%5Bbot%5D/received_events",
      "type": "Bot",
      "user_view_type": "public",
      "site_admin": false
    },
    "sha": "591b3e1ed3c8eedcfb2804cecde98243f8859aac",
    "ref": "591b3e1ed3c8eedcfb2804cecde98243f8859aac",
    "payload": {

    },
    "transient_environment": false,
    "production_environment": false,
    "performed_via_github_app": null
  }
]
